targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      nsf_v2|field_to_ui:
        enabled: true

builders:
  field_to_ui:
    import: "package:nsf_v2/application/builders/field_ui_builder.dart"
    builder_factories: ["fieldToUIBuilder"]
    build_extensions: {".dart": [".model.part"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]