targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
      nsf_v2|nsi_data:
        enabled: true

builders:
  nsi_data:
    import: "package:nsf_v2/application/builders/nsi_data_builder.dart"
    builder_factories: ["nsiDataBuilder"]
    build_extensions: {".dart": [".nsidata.dart"]}
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]